<form id="add-perso" method="post">
    <div class="form-group">
        <label for="name">Nom : </label><input type="text" name="name">
    </div>
    <div class="form-group">
        <input type="radio" id="tordu" name="genre" value="tordu" checked><label for="tordu"> Tordu machiavélique</label>
    </div>
    <div class="form-group">
        <input type="radio" id="bourrin" name="genre" value="bourrin"><label for="bourrin"> Bâtard bourrin</label>
    </div>
    <button type="submit" class="btn">Ajouter</button>
</form>
